# MathSnip Makefile
# Build and install MathSnip with configurable backend

# Configuration
BACKEND ?= texo-coreml
ARCH ?= $(shell uname -m)
VERSION := $(shell git describe --tags --always --dirty 2>/dev/null | sed 's/^v//' || echo "dev")
APP_NAME = MathSnip
APP_BUNDLE = $(APP_NAME).app
MODELS_DIR = models

# Available backends: texo-coreml, texo, pix2tex
# Override with: make BACKEND=texo build

.PHONY: setup build install clean help

help:
	@echo "MathSnip Build System"
	@echo ""
	@echo "Usage:"
	@echo "  make setup          - Set up the backend (default: $(BACKEND))"
	@echo "  make build          - Build MathSnip.app"
	@echo "  make install        - Build and install to /Applications"
	@echo "  make clean          - Clean build artifacts"
	@echo ""
	@echo "Backends:"
	@echo "  make BACKEND=texo-coreml install    (default)"
	@echo "  make BACKEND=texo install"
	@echo "  make BACKEND=pix2tex install"
	@echo ""
	@echo "Architecture:"
	@echo "  make ARCH=arm64 build               (default on Apple Silicon)"
	@echo "  make ARCH=x86_64 build              (Intel Mac)"
	@echo ""
	@echo "First time: make setup && make install"
	@echo "Current backend: $(BACKEND), arch: $(ARCH)"

setup:
ifeq ($(BACKEND),texo-coreml)
	cd backends/texo-coreml && ./setup.sh
else ifeq ($(BACKEND),texo)
	cd backends/texo && ./setup.sh
else ifeq ($(BACKEND),pix2tex)
	uv tool install pix2tex
else
	@echo "Error: Unknown backend '$(BACKEND)'"
	@echo "Available backends: texo-coreml, texo, pix2tex"
	@exit 1
endif

build:
	@echo "// Auto-generated by Makefile - DO NOT EDIT" > BackendConfig.swift
	@echo "// Backend: $(BACKEND)" >> BackendConfig.swift
	@echo "" >> BackendConfig.swift
ifeq ($(BACKEND),texo-coreml)
	@echo "let activeBackend: LaTeXBackend = .texoCoreml" >> BackendConfig.swift
else ifeq ($(BACKEND),texo)
	@echo "let activeBackend: LaTeXBackend = .texo" >> BackendConfig.swift
else ifeq ($(BACKEND),pix2tex)
	@echo "let activeBackend: LaTeXBackend = .pix2tex" >> BackendConfig.swift
endif
	@rm -rf $(APP_BUNDLE)
	@mkdir -p $(APP_BUNDLE)/Contents/MacOS
	@mkdir -p $(APP_BUNDLE)/Contents/Resources
	@cp assets/icon.png $(APP_BUNDLE)/Contents/Resources/
	@cp assets/icon@2x.png $(APP_BUNDLE)/Contents/Resources/
	@cp assets/AppIcon.icns $(APP_BUNDLE)/Contents/Resources/
	@cp assets/preview.html $(APP_BUNDLE)/Contents/Resources/
	@cp assets/katex.min.css $(APP_BUNDLE)/Contents/Resources/
	@cp assets/katex.min.js $(APP_BUNDLE)/Contents/Resources/
	@cp assets/tex2typst.min.js $(APP_BUNDLE)/Contents/Resources/
	@cp -r assets/fonts $(APP_BUNDLE)/Contents/Resources/
ifeq ($(BACKEND),texo-coreml)
	@if [ -d "$(MODELS_DIR)/Encoder.mlpackage" ]; then \
		cp -r $(MODELS_DIR)/Encoder.mlpackage $(APP_BUNDLE)/Contents/Resources/; \
		cp -r $(MODELS_DIR)/Decoder.mlpackage $(APP_BUNDLE)/Contents/Resources/; \
		if [ -f "$(MODELS_DIR)/vocab.json" ]; then \
			cp $(MODELS_DIR)/vocab.json $(APP_BUNDLE)/Contents/Resources/; \
		fi; \
	else \
		echo "Warning: CoreML models not found - run 'make setup' first"; \
	fi
endif
	@swiftc -o $(APP_BUNDLE)/Contents/MacOS/$(APP_NAME) \
		-target $(ARCH)-apple-macosx14.0 \
		-framework Cocoa \
		-framework ScreenCaptureKit \
		-framework WebKit \
		-framework CoreML \
		BackendConfig.swift \
		main.swift \
		AppDelegate.swift \
		OverlayPanel.swift \
		PreviewPanel.swift \
		backends/texo-coreml/MathSnipTokenizer.swift \
		backends/texo-coreml/CoreMLInference.swift
	@cp Info.plist $(APP_BUNDLE)/Contents/
	@/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $(VERSION)" $(APP_BUNDLE)/Contents/Info.plist
	@/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $(VERSION)" $(APP_BUNDLE)/Contents/Info.plist
	@echo "✓ Built $(APP_BUNDLE) v$(VERSION) with backend: $(BACKEND)"

install: build
	@cp -R $(APP_BUNDLE) /Applications/
	@echo "✓ Installed to /Applications/$(APP_BUNDLE)"

clean:
	@rm -rf $(APP_BUNDLE)
	@rm -f BackendConfig.swift
	@echo "✓ Clean complete"
